### ISSUE TITLE
Common Zenboard for all Squads

### ISSUE THREAD

**Issue by nkocsis** [zowe/community#1013]
I would like to be able to look at one place to get an accurate picture of all the issues being worked on. I would like to see this organized by Sprint and I would like to see the backlog as well

**Comment by Joe-Winchester** [comment]
@nkocsis - Zen hub allows you to add repos, and the most active squad ones are probably api-layer, zlux, zowe-cli, vscode-extension-for zowe, zowe-install-packaging, zss, docs-site, zowe-github-io, zowe-docker-files.  There will be others also so this isn't a complete list.
A big picture zenhub board could be created using filters.  I believe not every squad uses milestones and labels consistently so is your issue to try and collect data about how each squad tracks their items and then converge ?  If so this could be something for the TSC to consider, so including @balhar-jakub for his input.

**Comment by nkocsis** [comment]
@Joe-Winchester I already have a common board using the "Community" repo and I have 16 repos added to it so I can already track the boards but what is missing is a common agreement on how to use it as your correct that not all squads use Milestones.

**Comment by nkocsis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Next sprint](https://trello.com/c/YbA2y4BC/7-next-sprint)

**Comment by nkocsis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [API ML Item 1](https://trello.com/c/ni2vEtiC/4-api-ml-item-1)

**Comment by balhar-jakub** [comment]
The API ML squad is trying to move the whole planning and tracking process to the Community ZenHub board. 

The usage is as follows for the columns. We aren't using In Progress and In QA.
- New Issues - Contains the issues that we haven't decided on yet or that are being clarified by one of the squad members
- Icebox - Basically long term backlog. Issues that we want to solve at some point but not within this PI
- Backlog - Issues that we plan to look at in this Backlog but aren't planned for specific sprints
- Sprint1 -Sprint6 - Plans for the issues to be solved within the specific Sprint. 
- Closed - Closed and accepted issue

As for the Milestones:
- We add milestones to each issue that we plan to deliver for specific sprints

As for the Tags:
- We use the tag for specific PI to outline the goal to deliver within the PI e.g. 21PI1 should be delivered within PI1. 
- We use the squad tag to state that the squad intends to look at that at some point. 
- We use the community tag to state that the squad doesn't intend to work on the issue unless something change
- bug, enhancement, and question are tags outlining what type the issue is
- docs tag is used to outline that the issue touched docs-squad
- Good first issue shows the issues that are a good starting point for new contributors.

**Comment by balhar-jakub** [comment]
Linked to #481

**Comment by anton-brezina** [comment]
Useful report to consider for changelog generation is the Control Chart (i.e. for [API ML](https://app.zenhub.com/workspaces/community-5c93e02fa70b456d35b8f0ed/reports/control?df=&dr=14d&dt=&ep=Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzA&prs=false&r[]=145870120&r[]=162463317&r[]=143049506&r[]=144619729&r[]=152270012&r[]=300586575&r[]=150100207&r[]=176523400&r[]=141316148&r[]=144599701&r[]=144600062&r[]=151615191&r[]=151624320&r[]=168378275&r[]=144592776&r[]=144595426&r[]=166097436&sp=Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzE5NDEwNjM&s=day)). You can pick a date range for which you'd like to generate it and among other stuff it will generate a list of completed issues within that period.

**Comment by jellypuno** [comment]
Explorers is using Zenhub. We also updated the workflow so the community board will be updated whenever we move the cards
