### ISSUE TITLE
Cannot download Zowe NodeJS SDK. 

### ISSUE THREAD

**Issue by frankgiordano** [zowe/community#1134]
Selecting I agree at the following link to download the zip file for the SDK fails

https://zowe.jfrog.io/zowe/list/libs-release-local/org/zowe/download/legal.html?type=nodejs-sdk&version=1.20.1

{
  "errors" : [ {
    "status" : 404,
    "message" : "File not found."
  } ]
}

**Comment by balhar-jakub** [comment]
@MikeBauerCA Could someone from SDK or CLI group take a look?

**Comment by MikeBauerCA** [comment]
@zFernand0 could you review? I am receiving a 404 for both the Node & Python SDK

**Comment by MikeBauerCA** [comment]
@zFernand0 resolved the issue, thanks!

**Comment by frankgiordano** [comment]
in chrome when i click on link it does not download the file at all.. it shows a prompt on whether to open or cancel the zip file. I have to open it and then save.. I am using chrome.. Why not auto download automatically like everyone else does on chrome..

**Comment by zFernand0** [comment]
Will this be related to a Chrome setting?
chrome://settings/?search=downloading

**Comment by t1m0thyj** [comment]
> Why not auto download automatically like everyone else does on chrome..

The Zowe site isn't doing anything to deliberately make the download process require an extra click. This behavior is caused by either a bug with the site or an issue with your environment.

What did the prompt look like? If you're able to attach a screenshot, that would be helpful 🙂

Sometimes antivirus software can cause Chrome to flag downloads as suspicious, which makes you click an extra button to confirm the download:
![image](https://user-images.githubusercontent.com/22344007/115767303-f9f54000-a376-11eb-9518-bf54c67c8128.png)

**Comment by frankgiordano** [comment]
setting does not make a difference.. 

![image](https://user-images.githubusercontent.com/7764341/115768323-28274f80-a378-11eb-8903-1658c79ae1d4.png)

**Comment by frankgiordano** [comment]
ok i see it downloads it and opens it.. never mind.. thanks . lets mark this complete
