### ISSUE TITLE
How do we distinguish between the Core/Extending/External components?

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1207]
**Is your feature request related to a problem or limitation? Please describe.**
As a part of the Support Conformance Program, the supporters will have an option to state support of core components. 

As such ZLC is asking us to come up with a definition of a core component. 

The linked question is, what are the components that we actually have?

**Comment by balhar-jakub** [comment]
The discussion was leaning towards the statement that if a support vendor wants to have a badge for a specific version then the vendor supports the specific version. We will add new components only when releasing a new major version. We expect vendors to support the existing components as they evolve throughout the major version with minor and patch versions. 

The proposal is to define the core components as follows:

### v1

The v1 has three components. 

- z/OS component
- CLI component (Vendor-specific extensions are excluded)
- VS Explorer component

### v2 and further

When discussing new major version the TSC together with ZLC will identify potential new core components that are required for the badge for the given version.

**Comment by armstro** [comment]
What is core was discussed in the ZLC meeting today - let me try to summarize 

Core has various attributes - Core is cover by LTS policy and includes criteria the TSC determines makes the code "in good standing in the community" - my term and not blessed by TSC. Items include adequate documentation, included in regular build process, able to be tested via automation, good quality - (however determined by TSC), adequate staffing for viability in LTS. One attribute is to be vendor neutral other than using the inherent z/OS services (z/OSMF, FTP, etc.).  Core should only need z/OS. 

Discussion was on what is core today as test case for the attributes listed above (There is the need for some closure on how to package and how to count "components"). Personally I think "components" should have an eye towards "containers" in the future. 
 - API ML  
 - Desktop (Note: API ML and Desktop could be lumped together and counted as one - TBD) 
 - Zowe Explorer 
 - Core CLI because it prereqs only z/OSMF and the other "vendor neutral" extensions are SCS and FTP (SCS to be merged into Core CLI.) 
 - SDK for Node (Note: whether this is separate component that pre-reqs other components like CLI is TBD)  

Squads and TSC have the authority to grow these components as they see fit (HA using VSAM, Redis, are examples... )

There was acknowledgement that there is a category of Zowe open source that is vendor specific (CICS, IMS, Db2, MQ) that are not core but might be called "vendor extensions" that would fit almost all the same core criteria except for not being vendor neutral. 

Other "not core" components are incubators, samples, tech previews. How any "development tools" are classified is TBD. 

Comment made that may require additional discussion is no new components would be added until the next version boundary. If next version is a few months away that seems ok - if next version is 2 years away that seems a long time. Adding new components (the timing and criteria) likely needs some discussion.

**Comment by balhar-jakub** [comment]
The current version is in release policy document. 
The PR is here: https://github.com/zowe/community/pull/1213

**Comment by balhar-jakub** [comment]
I am closing this issue as for V1 it's been solved. For V2 it's being solved as part of the components maturity topic.
