### ISSUE TITLE
Stabilization/Migration/Deprication strategy for V2 ?

### ISSUE THREAD

**Issue by nkocsis** [zowe/community#1297]
How would v1 customers move to V2 ?

**Comment by balhar-jakub** [comment]
What upgrade paths will we support?

**Comment by balhar-jakub** [comment]
# Requirements

## Technical part

- We can release version 2 as snapshots
- We can release version 1 maintenance release
- We are able to develop breaking changes in a separate branch that's nevertheless built and provided
- We provide the migration path to the next release

## Non-technical part

- We need the consumers to be aware of the major release version schedule
- We need to notify extenders about the upcoming breaking changes
- We need to provide side by side documentation for multiple releases

# Solutions

## Technical Part

### Branching scheme and releasing 

- Main branch (staging) - developing and bringing non-breaking changes
   - On commit SNAPSHOT to active release is released e.g. for now to V 1.x
- V{Maintenance} - Cherry-picking the change to the branch from the main branch
   - Patch releases are released when a security fix needs to be integrated. 
- V{Next} - Main branch is merged on every commit to main. The merge happens automatically if possible, otherwise notifies the author. The breaking changes implemented here. 
   - On commit SNAPSHOT to next release in form v{Next}.0.0-SNAPSHOT e.g. v3.0.0-SNAPSHOT

### Migration path

What are we looking for? We need each squad to have a migration path documented for their components. 

## Non-technical part

- The schedule was published on https://www.zowe.org/download.html 
- The next major version release will be advertised on October Webinar, together with the webinar we should also promote on LinkedIn, Slack, other channels.
- We need to introduce V2 docs-site side by side with the V1 (reach out to docs-squad)
- Preparation of the slides to explain what changes are happening - Mike Bauer, Rose Sakach working on it.

**Comment by balhar-jakub** [comment]
Notes from docs-squad

- What’s the difference between v1 and v2, why users might want to upgrade. We need to make this clear in the docs.
- Since v2 will introduce breaking changes, so need to document the migration path and provide clear migration documentation on the doc site.
- We now have a list of v1 docs published online, with v2 do we have any plan to deprecate any of the previous versions or remove them online?
- Jumping to v2 might surprise some users who are not aware of the schedule. Wondering if we could do some kind of early communication on the doc site, similar to the upcoming release section on the Kubernetes site.

**Comment by balhar-jakub** [comment]
Transitions are here: https://broadcom.ent.box.com/notes/862731351262?s=8qhpmnuym8d5alhijlb1lsse6h520m62

**Comment by balhar-jakub** [comment]
There is a linked issue with the tooling:
https://github.com/zowe/zowe-install-packaging/issues/2565
