### ISSUE TITLE
Management of dependency security issues

### ISSUE THREAD

**Issue by jmertic** [zowe/community#1321]
I've noticed many of the repos have listed security vulnerabilities listed for dependencies; one example is https://github.com/zowe/api-layer. 

I'd like to see if the project has guideance or an effort to manage this. We also have an offering from the LF called Vulnerability Detection that might be worth adopting here as well that leverages snyk.io.

**Comment by nkocsis** [comment]
@jmertic John, I added this to the agenda to review at our next security call 10/20

**Comment by jmertic** [comment]
Great thank you! Let me know if having some of our resources at the LF ( thinking either someone like David Wheeler, or the team behind LFX Security ) would be helpful for that meeting.

**Comment by 1000TurquoisePogs** [comment]
Just adding one more point for the record: the amount of security issues shown in github itself is based upon analyzing a repos "primary branch". A primary branch could be a release branch, or an in-progress branch. If its the release branch, the security results could be 1 release outdated, versus the in-progress branch. So I'd recommend making "primary branch" equal to the very latest, rather than release code. Some repos use 1 branch for both purposes, also resolving the issue.

**Comment by balhar-jakub** [comment]
The current next step is to publish security vulnerabilities that were fixed in n-1 version on the Docs-site and zowe.org/security
