### ISSUE TITLE
Issue with MFA login

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1378]
**Describe the bug**
When trying to login with MFA to the Web Desktop the login fails. It seems that there are multiple failure modes how this is happening. 

The issue was raised by multiple people at the moment. We will keep the cases here until we have the solutions for the problems we are aware of. 

Issue Brought by Joe W. - handled by Jakub B. 
  - The customer can use the UI of the zOSMF to login with the MFA with the OTP
  - The customer case use the API ML authentication API to login with MFA and receives valid token
  - The customer can't login via ZLUX UI and as a part of the problem perceives the 5 tries to use the OTP in the ESM. 

Issue brought by Sean G. - Please provide some details.

**Comment by 1000TurquoisePogs** [comment]
One thing I've noticed is nobody should access the app-server directly if the app-server is also being hosted by gateway.
Even if it doesn't cause auth issues, it will cause end user confusion because a cookie originating on 8544 wont be readable on 7554 or vice versa, so things such as SSO become confusing or useless. If the gateway exists, nobody should be going to 8544. Were they? That might be part of the issue.

**Comment by balhar-jakub** [comment]
Closing the issue as stale.
