### ISSUE TITLE
Transitioning the zowe.org/vnext page

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1464]
Need a plan for this web page once V2 LTS is published

- Logically, once V2 is "active", _vnext_ represents V3, the information on this page will instantly be (possibly) out-of-date and confusing at best
- Technically:  there are areas within the wider website that reference links to this page, we need to be sure they are still relevant AND are not broken

Goal:  Proactively address this and be day-1 ready (4/25) 

Considerations:

- Short term:  Possible simple fix... add a banner at the top of the page that indicates V2 is NOW ACTIVE and the information on the page will be archived an a specific date OR note that it has been merged in with Zowe V2 docs
- Long term:  Wipe the page and simply reference the timeline for V3 until we have more relevant information

**Comment by nannanli** [comment]
Two quick updates: 

- The doc squad pulled the content in the Changes to the functionality section into the v2 release notes on the doc site. Here is a draft that we're working on: https://deploy-preview-1961--zowe-docs-master.netlify.app/stable/getting-started/release-notes/v2_0 so that part of  information could later be found on the doc site as well. 
- For the v2 office hours, doc squad has converted all of the available recordings into videos and later will be uploaded to the Youtube channel and linked from the doc site. So that part of information can also be accessed later.
- For the Conformance Criteria, we created a section in v2 release notes as well to link to the same set of PDF version of conformance criteria.

**Comment by balhar-jakub** [comment]
The transition is happening here: https://github.com/zowe/zowe.github.io/pull/825

**Comment by balhar-jakub** [comment]
The PR was merged and as such the transition is done as of now.
