### ISSUE TITLE
V2 retrospective

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1504]
We need to go through the whole process for announcing and releasing V2 Zowe and analyze what worked, what didn't work and where we can improve next time.

**Comment by balhar-jakub** [comment]
The work is happening here: https://ibm.box.com/s/ks19c29b0dtjctgzk6b19j2cwbm7er3e

**Comment by jackjia-ibm** [comment]
Comments from Systems/install-packaging point of view:

- In 21PI3, we planned and executed the task to propose v2 breaking changes and communicate with squads. This was done in PI3 and proposal was logged in github issue(s). Most of the items we got verbal agreements and few of changes we don't see objections so we move on to 21PI4 implementation.
- Here are brief timeline on zowe-install-packaging changes in 21PI4 and 22PI1.
  * Nov 2021 is the main month for v2 install-packaging new code added.
  * Systems squad provided a test v2 pax build around Dec 10, 2021 for squads to migrate their components.
    - This build can complete install/config on most of the systems with PKCS#12 keystore.
    - This build has APIML/jobs/files APIs migrated to v2 format already.
  * Around Jan 12, 2022, keyring support were added.
  * Around Jan 16, 2022, SMPE build was added. Due to some volume/copy issues, we eventually have SMPE build in early Feb.
  * Around Feb 17, 2022, required changes on zowe-install-packaging about containerization build were done.
    - We know containerization build is not in critical path to GA v2.
  * All the works after mid-Feb, 2022 were about migrating playbooks and test automation.
- So from our point of view,
  * There are no major code changes required on zowe-install-packaging is blocking GA v2 in Feb 2022. In Feb 2022, we already can use pipeline to build pax, SMPE and containers.
  * V2 install-packaging changes are complicated but mainly within install-packaging. What we ask on components are simple: manifest.yaml and 3 lifecycle scripts (start.sh, validate.sh and configure.sh).
    - Part of the plan was to consolidate environment variables, this does may complicate things, but:
    - I prepared APIML v2 migration in half day, and took another 2-3 hours to confirm with Andrej
    - It took me half hour to migrate simple components like jobs/files API to v2 format.
    - I can understand some components are complicated. Above are just what it took for v2 migration on APIML and jobs/files.
  * IMHO, without automated tests is inconvenient but not blocking issue to GA. We GAed v1 in similar way.
    - It will be inconvenient without tests to confirm PR, so a complicated PR may break components.
    - But I don't remember I revert any changes from zowe-install-packaging. So that means the changes are necessary and be compatible with what we discussed.
  * No any intention to say docs are not important or when docs should be prepared, that's out of Systems' scope. Just from install-packaging point of view, what we want to achieve is the package should be simple enough for user to complete install and configure without too much hassle. This is common experience on distributed software.
  * If we say 21PI3 communication is not good enough, the Systems squad meeting were held weekly from 22PI4 till nowadays to discuss issues. Maybe there are rooms we can still do better.
