### ISSUE TITLE
Prepare Q2 Webinar

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1572]
Find the correct topics and presenters for the next quarterly webinar.

**Comment by RASakach** [comment]
Title / Abstract sent to Mae
Waiting on OMP to book the Webinar and share a link so that we can begin socializing

Poll Question to be included:
1. What is your plan for Zowe V2 installation & adoption?
(a) Looking at this ASAP
(b) Probably at least 6 months out
(c)  More than 6 months out
(d)  When V1 is going off support
(e)  No plans / don't know

2.  Why are you waiting on Zowe V2 installation?
(a)  We're not waiting, we're ready
(b)  Staffing / shortage of folks to install
(c)   My organization has other priorities
(d)   My organization prefers to wait / too risky
(e)   My organization hasn't adopted Zowe yet
(f)    Other please comment: 
(e)   Don't know

**Comment by pdubz3** [comment]
(Mike - June 10) I'll take a shot at drafting the survey monkey questions for the webinar regarding plans to upgrade to V2.

**Comment by RASakach** [comment]
Webinar was held and recorded.  
Webinar link:  not yet available
Survey Link: https://www.surveymonkey.com/r/zowev2plans

Action item:  Post the recording and survey link to the Zowe Announcements

**Comment by RASakach** [comment]
Waiting on link to the recording.

**Comment by RASakach** [comment]
Recording Link:  [](https://www.youtube.com/watch?v=b6vloD0qwuk) is posted at zowe.org announcements.
Closing this as "COMPLETED".
