### ISSUE TITLE
How to test/install components that should not be a part of the Zowe distribution package?

### ISSUE THREAD

**Issue by achmelo** [zowe/community#1586]
Thank you for taking the time to submit a topic for the architecture call.
diff --git a/.github/ISSUE_TEMPLATE/tsc_requests.md b/.github/ISSUE_TEMPLATE/tsc_requests.md

**Comment by nkocsis** [comment]
@jackjia-ibm Any updates ?

**Comment by jackjia-ibm** [comment]
@achmelo there is way to install any extension for testing purpose. But it won't go deep to test the extension itself since it doesn't have the insights how to test it. But this test case can verify whether zowe can be started with this extension installed/enabled.

When you kick off [Zowe CICD Integration Tests](https://github.com/zowe/zowe-install-packaging/actions/workflows/cicd-test.yml),
![Screen Shot 2022-07-29 at 9 54 44 AM](https://user-images.githubusercontent.com/39711029/181775978-c6ce88ac-3a97-4273-821b-dca1d3f9b936.png)

- Choose Install Test - Extensions
- Custom Extension List - path/url to download your extension. Check here for details: https://github.com/zowe/zowe-install-packaging/blob/v2.x/master/.github/workflows/cicd-test-readme.md#custom-extension-list

fyi @FlappiTomic

**Comment by balhar-jakub** [comment]
Closing as the actual issue lives within zowe-install-packaging.
