### ISSUE TITLE
Can't connect to MVS explorer

### ISSUE THREAD

**Issue by GilPen** [zowe/community#1682]
**Describe the bug**

I can enter in the ZLUX but I can't login in MVS EXPLORER or USS EXPLORER. 
The message "Unexpected token < in JSON at position 0" appears

And the editor is searching for files all the time and never stops

I can't connect to the MVS Explorer endpoint even when using the gateway.

**Steps to Reproduce**

1. Everytime I want to login MVS Explorer from ZLUX or USS Explorer from ZLUX

**Expected behavior**
Just want to use MVS / USS Explorer

**Screenshots**
![Error_MVS_EXPLORER](https://user-images.githubusercontent.com/69505474/187173788-02fe0151-dc91-4ec1-978b-25f8453b7c76.jpg)

**Logs**
I
[appServer-2022-08-25-14-18.log](https://github.com/zowe/community/files/9443561/appServer-2022-08-25-14-18.log)

**Details**
 - ZOWE 2.2.0+20220714
 - ZOS 2.3 on a Z14 server
 - TSS
 - JAVA J8.0_64
 - nodejs v12.18
 - Browser Chrome

**Comment by 1000TurquoisePogs** [comment]
The URL you are accessing the MVS explorer from is not valid in V2. That is a V1 URL.
You can access the MVS explorer from either `https://host:7554/zlux/ui/v1/ZLUX/plugins/org.zowe.explorer-mvs/web/index.html` or within the desktop at `https://host:7554/zlux/ui/v1/`

However it is recommended to use the Desktop Editor instead of the MVS and USS explorers as it is the successor and where new development occurs. It is available at `https://host:7554/zlux/ui/v1/ZLUX/plugins/org.zowe.zlux.bootstrap/web/?pluginId=org.zowe.editor&showLogin=true` or in the desktop at `https://host:7554/zlux/ui/v1/`

**Comment by GilPen** [comment]
Hello 

No problem to use Desktop Editor.

But I get an error when I use the URL https://sysa.dns21.socgen:7554/zlux/ui/v1/ZLUX/plugins/org.zowe.zlux.bootstrap/web/?pluginId=org.zowe.editor&showLogin=true as well.
![image](https://user-images.githubusercontent.com/69505474/187356999-53370791-c3aa-4619-9a5e-3e9043cc0930.png)

Regards
Gilles Peniguel

**Comment by GilPen** [comment]
In the ZLUX, EDITOR is running and never stops 
![Errot_DESKTOP_EDITOR2](https://user-images.githubusercontent.com/69505474/187357492-532e171d-86fb-47d7-8f8d-5c7837fd9515.jpg)
?
