### ISSUE TITLE
Removal of ZOWE_IP_ADDRESS option in Zowe 2x causes problem for VIPA definition

### ISSUE THREAD

**Issue by m-kubik** [zowe/community#1772]
After migrating to Zowe V2.4 (from 1.x) I hit a problem with network.
For Zowe 1x I had VIPA definitions set, so the IP address was activated/deactivated on the LPAR whenever Zowe started task was started or stopped.

This does not work anymore and I suspect it's caused by removing of ZOWE_IP_ADDRESS option which is no longer available in 2.x

VIPA definition which is affected is:
VIPARange Define Moveable Disruptive 255.255.255.255  10.x.x.x

To connect to Zowe, I'm using DNS which points to the VIPA.
This all works fine on Zowe 1x, when I start STC, the IP address is automatically defined to LPAR where Zowe is running.

On V2.4, ports are opened on 0.0.0.0 and listening for connections, but the IP address is not created by the TCPIP stack.
I assume that's because in yaml file I have no specification for the IP but only the DNS name is given which probably does not cause "bind" in Zowe code.

**Comment by 1000TurquoisePogs** [comment]
I think there's different VIPA configurations that will fit the DNS-only solution that v2 has, but there are still ways to expose IP information in v2, at least partially.

This is going to have different answers per server.
The gateway, discovery, api-catalog had the following logic

https://github.com/zowe/api-layer/blob/v1.x.x/gateway-package/src/main/resources/bin/start.sh#L123-L130
Someone from the @zowe/api-mediation-committers group may have advice on that.

The app-server had this logic

https://github.com/zowe/zlux-app-server/blob/v1.x/master/bin/convert-env.sh#L108-L118

zss had this logic

https://github.com/zowe/zss/blob/v1.x/staging/c/zss.c#L1090


For app-server and zss, you can still assign specific IPs, because the underlying properties used in v1 still exist in v2, but in a YAML format. You can set:

```
components:
  app-server:
    node:
      https:
        ipAddresses:
          - "some ip"
    agent:
      host: "hostname or ip"
  zss:
    agent:
      https:
        ipAddresses:
          - "some ip"
```

**Comment by balhar-jakub** [comment]
@achmelo Can you answer for the API ML servers?

**Comment by m-kubik** [comment]
Hello,
thank you for suggestions with VIPA. Will be trying it today. For the problem with certificate I have now a Case opened with IBM.
Thanks
