### ISSUE TITLE
Approval for Zowe cutting SMF 83 records (+RAUDIX SAF resource) for Authentication audit

### ISSUE THREAD

**Issue by achmelo** [zowe/community#1783]
https://github.com/zowe/zowe-install-packaging/pull/3198

**Comment by 1000TurquoisePogs** [comment]
I would have vastly preferred that code regarding writing an SMF record be discussed in architecture or TSC calls BEFORE writing it as in https://github.com/zowe/api-layer/pull/2691
Now that we're here though, what we need to know is:

1. Why SMF 83? As this is within the IBM range and we're not IBM, what paper trail do we have to say that we're allowed to make an SMF 83 record? Did we get someone's permission?
2. Since this change needs RAUDITX permission to work, what happens if you don't have RAUDITX? Ideally this is an optional feature so that existing Zowe installs do not need to take action upon upgrade in order to continue using Zowe. Or else, at least we'll need to inform users in documentation (changelog!) and SMPE that this new resource is needed on a specific Zowe upgrade.

**Comment by balhar-jakub** [comment]
1. As far as I know, the specific record depends on the used ESM. For RACF it's 83, for TSS and ACF2 the number is different. The reason for using the ESM records is that we are doing ESM related authentication. 
2. If you don't have this permission the records won't be cut, that's all. I also believe that it's configurable and disabled by default. 

@JirkaAichler or @pj892031 may be able to provide more details.

**Comment by JirkaAichler** [comment]
I think Jakub provided all details.

There is the documentation for the manual Zowe upgrade. 
https://github.com/zowe/docs-site/blob/2fa83634cf441728ac36693fe885c1d56c95150d/docs/user-guide/api-mediation/api-mediation-smf.md

We may consider adding a link to it inside the changelog.

**Comment by JoeNemo** [comment]
I don't think it would pass review with ZOS security architects to use produce our own SMF 83's.   Unless the code is truly inside the ESM itself.

**Comment by JirkaAichler** [comment]
We are using R_auditx callable service that is intended to be used in such situations. It makes all authentication and authorization attempts be logged in one place. This is the standard way of producing authentication SMF audit records. 

https://www.ibm.com/docs/en/zos/2.5.0?topic=services-r-auditx-irrsax00-callable-service

**Comment by 1000TurquoisePogs** [comment]
This was discussed in this weeks architecture call and the summary is that we did get confirmation from some at IBM that the general solution that leads to SMF 83 is good and that SMF 83 itself is also good to use for this purpose, specifically either subtype 4 or to get our own subtype.

**Comment by nkocsis** [comment]
I will close this issue in a few days if no other comments
