### ISSUE TITLE
Clean-up access for departed Community Member(s)

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1897]
There is at least 1 known member with an ID that should be removed.

Let's use this issue to track the clean-up of any members who have confirmed they are no longer members of the Community.

**Comment by armstro** [comment]
@Joe-Winchester or @MarkAckert we discussed this briefly in the ZAC call today - this issue was raised since Peter Fandel has retired and we need someone with github admin authority to remove him. Can either of you do so? I don't know if there needs to be a wider review of departed committers? This would be a TSC issue to drive.

**Comment by MarkAckert** [comment]
Completed for Peter - I removed him from active squads and moved him to Emeritus. We do need a wider review, I found some long departed members still on the ZLC team and cleaned those up.

**Comment by armstro** [comment]
Thanks @MarkAckert ... I will close this issue for github - I don't know who in OMP might remove old names from slack or OMP listserv but we thought github was our community responsibility to administer.
