### ISSUE TITLE
Intel Linux server request to OMP for Zowe Chat build/test environment 

### ISSUE THREAD

**Issue by armstro** [zowe/community#2052]
Zowe chat is in need of Linux Intel environment for build and test. Can OMP assist?  What is the process? Cost? ZAC discussion for Aug 1st

**Comment by jmertic** [comment]
If we could get some specs on hardware requirements, we could likely support this. Let us know :-)

**Comment by MarkAckert** [comment]
Something small, around 2 CPUs and 8GB RAM would be sufficient for now... but if we can request up to 4/16 that would give us breathing room moving forward. Thanks!

**Comment by jmertic** [comment]
Thank you @MarkAckert - let me check on options and get back to you.

**Comment by MarkAckert** [comment]
Thanks John. In addition to or rather than a single box, would it be possible to acquire a small Kubernetes cluster? 

In the TSC call today we discussed promoting a containerized distribution of Zowe running on Kubernetes to `core` in context of Zowe v3 timeline. Right now we have a containerized distribution with Zowe v2 but it's marked as an `extension` project since we don't have the infrastructure to test it within the community. So solving infrastructure is a pre-req for us to promote Zowe containers to `core`. 

The Zowe Chat use case which kicked off this thread could also be solved using a K8S cluster.

**Comment by jmertic** [comment]
Let's work to scope this post-SHARE - we can likely accommodate this.

**Comment by jmertic** [comment]
So we potentially have use of DigitalOcean for this; I don't know if you want to focus on the primary use-case of Zowe Chat or explore something larger. Let me know your thoughts.

**Comment by MarkAckert** [comment]
I think we'd like something that can handle testing the containerized distribution of Zowe as well as Zowe Chat, with some room to grow on top. Zowe's Event Management is another activity which may want to make use of some x86 infrastructure in the near future. All of these projects can run on vanilla Kubernetes.

I can scope things with a bit more precision if you like, but as a rough watermark I think a cluster with 16GB RAM, 4 CPUs, ~500GB disk comfortably covers the requirements for everything have on our mind right now. I don't have any preference for CPU generation or node count within the cluster.

**Comment by jmertic** [comment]
Could you take a look at https://www.digitalocean.com/pricing/kubernetes and see what node types align? We are getting some credits from DO and need to negotiate how many with them based upon needs.

**Comment by jmertic** [comment]
Hi! That should be fine. Thinking it might be easier to give you account access to set this up; let me know if that works for you.

**Comment by MarkAckert** [comment]
That works for me, thanks

**Comment by MarkAckert** [comment]
Infra is now up and running, so I'll close this issue. Requests for cluster access can come through the systems squad.
