### ISSUE TITLE
Standalone Zowe CLI Installer on Zowe.org

### ISSUE THREAD

**Issue by jelaplan** [zowe/community#25]
Change the download and install for Zowe by separating the zOS components and the Zowe CLI so that user can download the latter separately. 

See E-mail Thread titled 
Re: [zowe/zlc] Allow CLI as separate download (#54)

**Comment by jelaplan** [comment]
See also Doc story
https://waffle.io/zowe/zowe-cli/cards/5bdb0d14a0271f001c9aad0c

**Comment by jackjia-ibm** [comment]
@jelaplan I've created a test link https://zowe.org/download-copy/, please take a look. Also the legal link has been updated for CLI.

The issue now is the download button generated by WordPress SiteOrigin Button doesn't support 2 rows of text. I'm not sure if you have more experience here. Please let me know, otherwise I can try something else, like rich text to put customized html. Thanks.

Once this is fixed and at the release date, we can copy the modified content (2 rows with buttons) to current download page. (That's another issue we cannot replace old page with the new created as far as I know.)

**Comment by jelaplan** [comment]
This story was completed on Thur Nov 15, 2018
