### ISSUE TITLE
Make tn3270-ng2 work as stand-alone

### ISSUE THREAD

**Issue by PeterHalsted** [zowe/community#294]
As an alternative to x3270, it would be great if the tn3270-ng2 could run in the browser as a stand-alone solution, without having to load the complete Zowe Desktop. Further, as x3270 has a scripting API for integrating and automating small tasks, so should tn3270-ng2, but it should be JavaScript and this would also require tn3270-ng2 to be wrapable in an iframe or as a Web Component on a master page - e.g. fitting into the Micro Frontend concept. 

This would make tn3270-ng2 the first and probably only open source web-based 3270 emulator.

There are of course alternatives that do such features, but none of them are open sourced and they all require a middle tier server for translating between HTTP and TN3270 - except for Rocket BlueZone Web, which should be able to connect using Zowe.

According to a trusted source in the Information Technology Research industry, there is a decline in the amount of vendors in the 3270 emulator space and they think that most if not all vendors will have disappeared from the market within 5 years from now. If this happens, it would be even more vital that there exist open source emulators that those still having the needs, will be able to turn to and continue development on.

**Comment by 1000TurquoisePogs** [comment]
Hi Peter, in Zowe 1.5.0, we're making it easier to get to something that's similar to stand-alone mode. It's a work in progress, but the idea is that you dont need to use the Desktop to use Zowe Apps.
The feature is that you take the ID of any app, and you utilize it as a query parameter to the Zowe App Server. For the terminal, it is:
/ZLUX/plugins/org.zowe.zlux.bootstrap/web/?pluginId=org.zowe.terminal.tn3270
This will give you the app without any additional UI, such as in this image:
![image.png](https://images.zenhubusercontent.com/5ca760660102ad60918e8aa1/c1d8acf0-d8d5-45b7-9e3e-e97c2aeafb98)

There are still some issues to fix with this mode... mainly that it doesn't give a login prompt yet and the window title is not the app title, it still says "zowe desktop". We hope to fix that in a release soon.

However, apart from that, the terminal can't be "stand-alone" in the sense that it would work without Zowe, as it requires a server-side tool to read the TCP socket. We hold this within the plugin called "terminal-proxy" (https://github.com/zowe/zlux-server-framework/blob/master/plugins/terminal-proxy) because we figure it is applicable to more than just this one terminal! We hope that other vendors & developers find that helpful in separating the implementation from the plumbing.

**Comment by PeterHalsted** [comment]
Looks cool :) And exactly what I meant and hoped for - I didn't mean that it should run without the Zowe backend, but that it should be able to run without the Zowe desktop fronten part drawn on the screen.

Do you know when it will be possible to use other EBCDIC tables like e.g. 1142 (277 with Euro sign)? 

Thanks a lot for the good news and looking forward to try it out :)

**Comment by 1000TurquoisePogs** [comment]
Oh, by the way it was coincidentally easy to make the tab stop saying "Zowe Desktop" and add a login prompt, perhaps this goes into the release after 1.5.0: https://github.com/zowe/zlux-app-manager/pull/162

**Comment by PeterHalsted** [comment]
Sounds great!

What about support for other EBCDIC tables?

And would it be possible through a script API or through eventing to automate tasks and e.g. make deep navigation into 3270 screens from another web page?

**Comment by DivergentEuropeans** [comment]
@1000TurquoisePogs Should this be closed?
